akash-network/community

.github/workflows/wip.yaml
Signed-off-by: Artur Troian <troian.ap@gmail.com>
=> ci: track WIP PRs

sig-clients/README.md, sig-clients/meetings/001-2023-01-19.md
=> sig-clients: add notes for meeting #1

README.md, cg-list/README.md, committee-steering/README.md
- Added Folder
- Added README content
- added references from community main README and from cg-list.md
Need to add links to meeting minutes, transcript and video once available from @brewsterdrinkwater
=> steering committee - initial commit

sig-clients/README.md
=> chore: reformat sig-client meeting table

wg-client-libraries/README.md
This PR initializes the Client Libraries Working Group.
=> Initialize wg-client-libraries

sig-design/README.md
This PR Initializes the SIG Design.
Please add any relevant leads and change proposals.
CC: @andreia-rodrigues @anilmurty
=> Initialize sig-design

wg-gpu/prd.md
=> chore: fix formatting with wp-gpu / prd

sig-documentation/documentation-structure.md
This PR introduces the structure of the Akash Netowork Documentation 2.0
=> WIP Documentation Structure

wg-content-moderation/meetings
Add meetings file to wg-content-moderation
Signed-off-by: Cheng Wang <68354230+lechenghiskhan@users.noreply.github.com>
=> chore: add meetings file to wg-content-moderation

sig-providers/README.md
added: meeting recording
pending in subsequent update: notes and transcript 
Signed-off-by: Cheng Wang <68354230+lechenghiskhan@users.noreply.github.com>
=> chore: add meeting table and links

wg-content-moderation/README.md
Add meeting table and details.
Notes and transcript links pending in subsequent changes.
Signed-off-by: Cheng Wang <68354230+lechenghiskhan@users.noreply.github.com>
=> chore: add meeting table and details

wg-gpu/README.md
=> fix(wg-gpu): fix broken links for related sigs

sig-economics/README.md, sig-economics/meetings/1-2023-02-01.md
=> chore (sig-economics): add meeting #1 agenda

sig-economics/meetings/1-2023-02-01.md
Signed-off-by: Hewi <121134490+heyhewi@users.noreply.github.com>
=> added recording link

wg-content-moderation/meeting minutes/2022-12-22.md
- create summary and notes for content moderation working group meeting 1
- update formatting 
- create metadata
Signed-off-by: Cheng Wang <68354230+lechenghiskhan@users.noreply.github.com>
=> chore: notes for content moderation wg, meeting 1

sig-chain/meetings/001-2023-02-08.md
Signed-off-by: Anil Murty <19495789+anilmurty@users.noreply.github.com>
=> sig-chain meeting notes for 2023-02-08.md

sig-providers/meetings/001-2023-01-25.md
Signed-off-by: figurestudios <64747030+figurestudios@users.noreply.github.com>
https://github.com/akash-network/community/issues/50
=> chore: add notes to sig-providers

wg-gpu/README.md, wg-gpu/progress.md
Signed-off-by: Artur Troian <troian.ap@gmail.com>
=> add gpu progress

sig-education/README.md
Signed-off-by: Drinkwater <brewsterdrinkwater@users.noreply.github.com>
=> create new sig-education repo with readme file

wg-README-template.md
Signed-off-by: Drinkwater <brewsterdrinkwater@users.noreply.github.com>
=> wg-readme: add the meeting table to the template

wg-client-libraries/meetings/001-2023-02-07.md
added detail notes and action items for wg-client-libraries meeting 1. 
Signed-off-by: Drinkwater <brewsterdrinkwater@users.noreply.github.com>
=> wg-client-libraries updates to detailed notes and action items

sig-education/meetings/001-2023-02-14.md
add agenda and meeting details before sig-education meeting 
Signed-off-by: Drinkwater <brewsterdrinkwater@users.noreply.github.com>
=> create sig-education meeting notes template for 2023-02-14

sig-education/meetings/001-2023-02-14.md
Recording is still rendering in Akord.
=> sig-education meeting 1 updates to detailed notes, transcript, and meeting details

sig-clients/meetings/002-2023-02-15.md
added meeting details, participants, transcript, and detailed notes. Recording coming soon.
=> sig-clients meeting #2 notes creation 2023-02-15

sig-support/meetings/002-2023-02-15.md
Added meeting details, transcript, and detailed notes. Waiting to add video recording.
=> sig-support meeting #2 2023-02-15 creation of notes.

sig-analytics/meetings/001-2023-02-09.md
sig-analytics meeting notes for 2023-02-09 with recording, detailed notes, transcript with support from Jin.
=> sig-analytics meeting 1 notes created

sig-analytics/README.md
added links for transcript, notes and recordin to readme meeting table for meeting 1
=> sig-analytics meeting 1 table update with all links

sig-clients/meetings/002-2023-02-15.md
added recording link to notes for meeting 2
=> sig-clients 2023-02-015 recording link updated

sig-clients/README.md
updated links for transcript, notes, and recording for meeting 2
=> sig-clients meeting links updated for meeting 2 in meeting table

sig-support/README.md
updates to transcript, notes, and recording link for meeting 2
=> sig-support readme updates for meeting 2 on meeting table

sig-support/meetings/002-2023-02-15.md
Added recording link for meeting 02-2023-02-15
=> sig-support meeting 2 update to recording link

wg-akash-hackathon/README.md
adding notes from wg-akash-hackathon meeting 1, after new repo is made. cc: @anilmurty
=> wg-akash-hackathon repo creation with readme

wg-akash-website/meetings/001-2023-02-21.md
added meeting details and agenda for taking notes during the meeting.
=> wg-akash-website meeting creation 001-2023-02-21.md

sig-design/meetings/002-02-21-.md
Create  md for sig-design meeting 2 including agenda and meeting details
=> sig-design meeting 2 pre-meeting creation

sig-providers/meetings/002-2023-02-22.md
created sig-providers meeting 2 with agenda and meeting time details.
=> sig-providers meeting 2 creation and agenda development

committee-steering/README.md
added date and time for steering committee monthly meeting 2
=> steering-committee updated readme with meeting 2 date

committee-steering/meetings/002-2023-02-23.md
add meeting details, and pre meeting notes md for meeting 2
=> committee-steering meeting 2: create notes file

sig-providers/meetings/002-2023-02-22.md
Add transcript and meeting recording to notes. @figurestudios will add detail notes
=> sig-providers 02-2023-02-22 notes update

sig-design/README.md
added links for meeting 2 notes, transcript, recording.
=> sig-design: readme update for meeting 2 links

committee-steering/meetings/002-2023-02-23.md
added detailed notes directly from meeting.
=> committee-steering 02-2023-02-23 detailed notes version 1

sig-documentation/meetings/002-2023-02-28.md
=> sig-documentation meeting 2 premeeting create: 02-2023-02-28.md

wg-content-moderation/meetings/2023-02-08.md
=> wg-content-moderation: added 04-2023-02-08 video recording

wg-content-moderation/meetings/05-2023-02-28.md
add agenda and meeting details
=> wg-content-moderation create premeeting 05-2023-02-28.md

wg-content-moderation/meetings/05-2023-02-28.md
added detailed notes and action items from wg-content-moderation meeting 5
=> wg-content-moderation: 05-2023-02-28.md live meeting notes v1

sig-economics/README.md
add time and date for meeting 2 to readme meeting table
=> sig-economics: meeting table updates for meeting 2 time and date

sig-support/meetings/003-2023-03-01.md
added agenda and meeting details pre-meeting
=> sig-support 003-2023-03-01.md pre-meeting notes created

wg-akash-website/meetings/001-2023-02-21.md
added participants, transcript, recording. Detailed notes coming soon.
=> wg-akash-website 001-2023-02-21.md meeting updates

sig-support/meetings/003-2023-03-01.md
added transcript to meeting 3 notes
=> sig-support 003-2023-03-01.md added transcript

committee-steering/meetings/002-2023-02-23.md
added recording link from arweave
=> committee-steering: 002-2023-02-23.md recording link added

sig-documentation/meetings/002-2023-02-28.md
added transcript, meeting recording and meeting details. @figurestudios to add detail notes and action items.
=> sig-documentation 02-2023-02-28.md meeting updates post meeting

sig-documentation/README.md
added meeting 2 notes and recording link. transcript link in PR
=> sig-documentation readme meeting 2 update to table

sig-support/README.md
updated meeting links for meeting 3. Added meeting 4 with date as well. 
In the future, I will update with the notes, but this was a legacy item.
=> sig-support readme links updated in meeting table for meeting 3

sig-analytics/onchain-data-model.md, sig-analytics/prd.md
- PRD-1.0 
- Structure for the data model spec (to be finalized with Jin Lim & Others)
=> [WIP] Analytics PRD + On-Chain data model/ schema

wg-content-moderation/README.md
updated all links with new naming, and added meeting 5 links to meeting table.
=> wg-content-moderation: meeting detail links updated

sig-providers/README.md
add links for transcript, notes, and video recording.
=> sig-providers: meeting 2 details added to readme

wg-content-moderation/meetings/05-2023-02-28.md
changed note structure and added transcript link
=> wg-content-moderation 005-2023-02-28.md updated notes

sig-analytics/meetings/002-2023-03-09.md
add meeting agenda and meeting details prior to meeting
=> sig-analytics: 002-2023-03-09.md notes created

sig-chain/meetings/002-2023-03-07.md
=> sig-chain meeting 2 002-2023-03-07.md created

sig-design/meetings/003-2023-03-08.md
added transcript and recording
=> sig-design 003-2023-03-08.md updates

wg-akash-website/meetings/002-2023-03-07.md
pre meeting file created for wg-akash-website working session #2
=> wg-akash-website 002-2023-03-07.md created

sig-analytics/meetings/002-2023-03-09.md
Manual review and cleanup of transcription
=> Transcription cleanup, minor note edits

sig-clients/meetings/003-2023-03-15.md
=> sig-clients 003-2023-03-15.md pre meeting

sig-support/meetings/004-2023-03-15.md
=> sig-support create 004-2023-03-15.md

sig-providers/meetings/003-2023-03-22.md
=> sig-provider 003-2023-03-22.md meeting creation

committee-steering/meetings/003-2023-03-28.md
added agenda, and pre meeting structure for note taking
=> committee-steering pre-meeting 003-2023-03-28.md

sig-documentation/meetings/003-2023-03-28.md
added pre meeting notes. 
I will add meeting transcript and recording following the meeting. 
@figurestudios will add detail notes.
=> sig-docs meeting 003-2023-03-15.md created

sig-support/meetings/005-2023-03-29.md
meeting notes for 5th bi weekly sig-support meeting
=> sig-support 005-2023-03-29.md created

projects-list/README.md
This PR updates the project list to reflect Quasarch's efforts.
=> Update project list

sig-chain/meetings/003-2023-04-04.md
=> sig-chain 003-2023-04-04.md

sig-clients/README.md, sig-clients/praetor/README.md
=> Anilmurty/sig clients/provider clients update

sig-clients/meetings/004-2023-04-19.md
=> sig-clients: 004-2023-04-19.md

sig-support/meetings/006-2023-04-12.md
=> sig-support: 006-2023-04-12.md

sig-providers/meetings/005-2023-05-24.md
=> Create sig-provider 005-2023-05-24.md

sig-support/meetings/009-2023-05-24.md
=> Create sig-support biweekly 009-2023-05-24.md

wg-gpu/GPU-AI-Incentivized-Testnet.md
Added draft incentivized testnet plan. 
Will update with incentives in the next few days (but we can review and merge this so that people can view/ read it)
=> Akash GPU and AI Incentivized Testnet Plan

committee-steering/meetings/005-2023-05-25.md
=> committee-steering Update 005-2023-05-25.md

sig-chain/meetings/005-2023-06-06.md
=> sig-chain Create 005-2023-06-06.md

sig-design/meetings/007-2023-07-12.md
=> sig-design Create 007-2023-07-12.md

sig-providers/meetings/007-2023-07-26.md
=> sig-providers: Create 007-2023-07-26.md

sig-economics/meetings/007-2023-08-02.md
=> sig-economics Create 007-2023-08-02.md

wg-provider-attributes/README.md
- Added links to provider attribute schema
=> wg-provider-attribute update

sig-clients/client-libraries/akashjs-cloudmos-console.md
Initial draft of document outlining areas of common functionality and where they will be archived for common use
=> Documenting common feature areas for cloudmos and console

committee-steering/meetings/008-2023-08-30.md
=> steering committee: Create 008-2023-08-30.md

sig-chain/meetings/008-2023-09-05.md
=> sig-chain Create 008-2023-09-05.md

sig-support/meetings/016-2023-08-30.md
=> sig-support Create 016-2023-08-30.md

sig-documentation/meetings/008-2023-08-22.md
=> sig-docs Create 008-2023-08-22.md

sig-support/meetings/017-2023-09-13.md
=> sig-support Create 017-2023-09-13.md

committee-steering/meetings/009-2023-09-28.md
=> Steering Committee: Create 009-2023-09-28.md

sig-providers/meetings/009-2023-09-27.md
=> sig-providers Create 009-2023-09-27.md

sig-clients/meetings/009-2023-09-20.md, sig-clients/meetings/010-2023-10-18.md
=> sig-clients Create 009-2023-09-20.md

committee-steering/meetings/010-2023-11-01.md
=> steering committee Create 010-2023-11-01.md

product-strategy/praetor-akash-provider-console-strategy.md
Draft based on discussions with Praetor team & Akash Core team
=> Draft Praetor & Akash Provider Product Strategy
